CREATE TABLE `t_zone` (
  `zone` varchar(20) DEFAULT '' COMMENT '区号',
  `name` varchar(50) NOT NULL DEFAULT '' COMMENT '名称',
  `position` smallint(6) DEFAULT '0' COMMENT '位置',
  `cn_name` varchar(20) DEFAULT NULL,
  `status` tinyint(2) DEFAULT '0' COMMENT '状态 0不使用 1使用',
  `cn` varchar(2)  DEFAULT '' comment '中文字母',
  PRIMARY KEY (`name`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 comment '区号';



-- ----------------------------
-- Records of t_zone
-- ----------------------------
INSERT INTO `t_zone` VALUES ('93', 'Afghanistan', 11, '阿富汗', 1, 'A');
INSERT INTO `t_zone` VALUES ('355', 'Albania', 12, '阿尔巴尼亚', 1, 'A');
INSERT INTO `t_zone` VALUES ('213', 'Algeria', 13, '阿尔及利亚', 1, 'A');
INSERT INTO `t_zone` VALUES ('376', 'Andorra', 14, '安道尔共和国', 1, 'A');
INSERT INTO `t_zone` VALUES ('244', 'Angola', 15, '安哥拉', 1, 'A');
INSERT INTO `t_zone` VALUES ('1264', 'Anguilla', 16, '安圭拉岛', 1, 'A');
INSERT INTO `t_zone` VALUES ('1268', 'Antigua and Barbuda', 17, '安提瓜和巴布达', 1, 'A');
INSERT INTO `t_zone` VALUES ('54', 'Argentina', 18, '阿根廷', 1, 'A');
INSERT INTO `t_zone` VALUES ('374', 'Armenia', 184, '亚美尼亚', 1, 'Y');
INSERT INTO `t_zone` VALUES ('247', 'Ascension', 19, '阿森松', 1, 'A');
INSERT INTO `t_zone` VALUES ('61', 'Australia', 20, '澳大利亚', 1, 'A');
INSERT INTO `t_zone` VALUES ('43', 'Austria', 21, '奥地利', 1, 'A');
INSERT INTO `t_zone` VALUES ('994', 'Azerbaijan', 22, '阿塞拜疆', 1, 'A');
INSERT INTO `t_zone` VALUES ('1242', 'Bahamas', 30, '巴哈马', 1, 'B');
INSERT INTO `t_zone` VALUES ('973', 'Bahrain', 31, '巴林', 1, 'B');
INSERT INTO `t_zone` VALUES ('880', 'Bangladesh', 110, '孟加拉国', 1, 'M');
INSERT INTO `t_zone` VALUES ('1246', 'Barbados', 32, '巴巴多斯', 1, 'B');
INSERT INTO `t_zone` VALUES ('375', 'Belarus', 33, '白俄罗斯', 1, 'B');
INSERT INTO `t_zone` VALUES ('32', 'Belgium', 34, '比利时', 1, 'B');
INSERT INTO `t_zone` VALUES ('501', 'Belize', 35, '伯利兹', 1, 'B');
INSERT INTO `t_zone` VALUES ('229', 'Benin', 36, '贝宁', 1, 'B');
INSERT INTO `t_zone` VALUES ('1441', 'Bermuda Is.', 37, '百慕大群岛', 1, 'B');
INSERT INTO `t_zone` VALUES ('591', 'Bolivia', 38, '玻利维亚', 1, 'B');
INSERT INTO `t_zone` VALUES ('267', 'Botswana', 39, '博茨瓦纳', 1, 'B');
INSERT INTO `t_zone` VALUES ('55', 'Brazil', 40, '巴西', 1, 'B');
INSERT INTO `t_zone` VALUES ('673', 'Brunei', 169, '文莱', 1, 'W');
INSERT INTO `t_zone` VALUES ('359', 'Bulgaria', 41, '保加利亚', 1, 'B');
INSERT INTO `t_zone` VALUES ('226', 'Burkina-faso', 42, '布基纳法索', 1, 'B');
INSERT INTO `t_zone` VALUES ('95', 'Burma', 111, '缅甸', 1, 'M');
INSERT INTO `t_zone` VALUES ('257', 'Burundi', 43, '布隆迪', 1, 'B');
INSERT INTO `t_zone` VALUES ('237', 'Cameroon', 90, '喀麦隆', 1, 'K');
INSERT INTO `t_zone` VALUES ('1', 'Canada', 81, '加拿大', 1, 'J');
INSERT INTO `t_zone` VALUES ('1345', 'Cayman Is.', 91, '开曼群岛', 1, 'K');
INSERT INTO `t_zone` VALUES ('236', 'Central African Republic', 196, '中非共和国', 1, 'Z');
INSERT INTO `t_zone` VALUES ('235', 'Chad', 197, '乍得', 1, 'Z');
INSERT INTO `t_zone` VALUES ('56', 'Chile', 198, '智利', 1, 'Z');
INSERT INTO `t_zone` VALUES ('86', 'China', 0, '中国', 1, 'Z');
INSERT INTO `t_zone` VALUES ('57', 'Colombia', 66, '哥伦比亚', 1, 'G');
INSERT INTO `t_zone` VALUES ('242', 'Congo', 67, '刚果', 1, 'G');
INSERT INTO `t_zone` VALUES ('682', 'Cook Is.', 92, '库克群岛', 1, 'K');
INSERT INTO `t_zone` VALUES ('506', 'Costa Rica', 68, '哥斯达黎加', 1, 'G');
INSERT INTO `t_zone` VALUES ('53', 'Cuba', 69, '古巴', 1, 'G');
INSERT INTO `t_zone` VALUES ('357', 'Cyprus', 142, '塞浦路斯', 1, 'S');
INSERT INTO `t_zone` VALUES ('420', 'Czech Republic', 82, '捷克', 1, 'J');
INSERT INTO `t_zone` VALUES ('45', 'Denmark', 53, '丹麦', 1, 'D');
INSERT INTO `t_zone` VALUES ('253', 'Djibouti', 83, '吉布提', 1, 'J');
INSERT INTO `t_zone` VALUES ('1890', 'Dominica Rep.', 54, '多米尼加共和国', 1, 'D');
INSERT INTO `t_zone` VALUES ('593', 'Ecuador', 58, '厄瓜多尔', 1, 'E');
INSERT INTO `t_zone` VALUES ('20', 'Egypt', 23, '埃及', 1, 'A');
INSERT INTO `t_zone` VALUES ('503', 'EI Salvador', 143, '萨尔瓦多', 1, 'S');
INSERT INTO `t_zone` VALUES ('372', 'Estonia', 24, '爱沙尼亚', 1, 'A');
INSERT INTO `t_zone` VALUES ('251', 'Ethiopia', 25, '埃塞俄比亚', 1, 'A');
INSERT INTO `t_zone` VALUES ('679', 'Fiji', 60, '斐济', 1, 'F');
INSERT INTO `t_zone` VALUES ('358', 'Finland', 61, '芬兰', 1, 'F');
INSERT INTO `t_zone` VALUES ('33', 'France', 62, '法国', 1, 'F');
INSERT INTO `t_zone` VALUES ('594', 'French Guiana', 63, '法属圭亚那', 1, 'F');
INSERT INTO `t_zone` VALUES ('689', 'French Polynesia', 64, '法属玻利尼西亚', 1, 'F');
INSERT INTO `t_zone` VALUES ('241', 'Gabon', 84, '加蓬', 1, 'J');
INSERT INTO `t_zone` VALUES ('220', 'Gambia', 70, '冈比亚', 1, 'G');
INSERT INTO `t_zone` VALUES ('995', 'Georgia', 71, '格鲁吉亚', 1, 'G');
INSERT INTO `t_zone` VALUES ('49', 'Germany', 55, '德国', 1, 'D');
INSERT INTO `t_zone` VALUES ('233', 'Ghana', 85, '加纳', 1, 'J');
INSERT INTO `t_zone` VALUES ('350', 'Gibraltar', 199, '直布罗陀', 1, 'Z');
INSERT INTO `t_zone` VALUES ('30', 'Greece', 176, '希腊', 1, 'X');
INSERT INTO `t_zone` VALUES ('1809', 'Grenada', 72, '格林纳达', 1, 'G');
INSERT INTO `t_zone` VALUES ('1671', 'Guam', 73, '关岛', 1, 'G');
INSERT INTO `t_zone` VALUES ('502', 'Guatemala', 170, '危地马拉', 1, 'W');
INSERT INTO `t_zone` VALUES ('224', 'Guinea', 86, '几内亚', 1, 'J');
INSERT INTO `t_zone` VALUES ('592', 'Guyana', 74, '圭亚那', 1, 'G');
INSERT INTO `t_zone` VALUES ('509', 'Haiti', 75, '海地', 1, 'H');
INSERT INTO `t_zone` VALUES ('504', 'Honduras', 76, '洪都拉斯', 1, 'H');
INSERT INTO `t_zone` VALUES ('852', 'Hongkong', 1, '香港', 1, 'X');
INSERT INTO `t_zone` VALUES ('36', 'Hungary', 178, '匈牙利', 1, 'X');
INSERT INTO `t_zone` VALUES ('354', 'Iceland', 44, '冰岛', 1, 'B');
INSERT INTO `t_zone` VALUES ('91', 'India', 185, '印度', 1, 'Y');
INSERT INTO `t_zone` VALUES ('62', 'Indonesia', 186, '印度尼西亚', 1, 'Y');
INSERT INTO `t_zone` VALUES ('98', 'Iran', 187, '伊朗', 1, 'Y');
INSERT INTO `t_zone` VALUES ('964', 'Iraq', 188, '伊拉克', 1, 'Y');
INSERT INTO `t_zone` VALUES ('353', 'Ireland', 26, '爱尔兰', 1, 'A');
INSERT INTO `t_zone` VALUES ('972', 'Israel', 189, '以色列', 1, 'Y');
INSERT INTO `t_zone` VALUES ('39', 'Italy', 190, '意大利', 1, 'Y');
INSERT INTO `t_zone` VALUES ('225', 'Ivory Coast', 93, '科特迪瓦', 1, 'K');
INSERT INTO `t_zone` VALUES ('1876', 'Jamaica', 191, '牙买加', 1, 'Y');
INSERT INTO `t_zone` VALUES ('81', 'Japan', 139, '日本', 1, 'R');
INSERT INTO `t_zone` VALUES ('962', 'Jordan', 192, '约旦', 1, 'Y');
INSERT INTO `t_zone` VALUES ('855', 'Kampuchea (Cambodia )', 87, '柬埔寨', 1, 'J');
INSERT INTO `t_zone` VALUES ('327', 'Kazakstan', 77, '哈萨克斯坦', 1, 'H');
INSERT INTO `t_zone` VALUES ('254', 'Kenya', 94, '肯尼亚', 1, 'K');
INSERT INTO `t_zone` VALUES ('82', 'Korea', 78, '韩国', 1, 'H');
INSERT INTO `t_zone` VALUES ('965', 'Kuwait', 95, '科威特', 1, 'K');
INSERT INTO `t_zone` VALUES ('331', 'Kyrgyzstan', 88, '吉尔吉斯坦', 1, 'J');
INSERT INTO `t_zone` VALUES ('856', 'Laos', 97, '老挝', 1, 'L');
INSERT INTO `t_zone` VALUES ('371', 'Latvia', 98, '拉脱维亚', 1, 'L');
INSERT INTO `t_zone` VALUES ('961', 'Lebanon', 99, '黎巴嫩', 1, 'L');
INSERT INTO `t_zone` VALUES ('266', 'Lesotho', 100, '莱索托', 1, 'L');
INSERT INTO `t_zone` VALUES ('231', 'Liberia', 101, '利比里亚', 1, 'L');
INSERT INTO `t_zone` VALUES ('218', 'Libya', 102, '利比亚', 1, 'L');
INSERT INTO `t_zone` VALUES ('423', 'Liechtenstein', 103, '列支敦士登', 1, 'L');
INSERT INTO `t_zone` VALUES ('370', 'Lithuania', 104, '立陶宛', 1, 'L');
INSERT INTO `t_zone` VALUES ('352', 'Luxembourg', 105, '卢森堡', 1, 'L');
INSERT INTO `t_zone` VALUES ('853', 'Macao', 2, '澳门', 1, 'A');
INSERT INTO `t_zone` VALUES ('261', 'Madagascar', 112, '马达加斯加', 1, 'M');
INSERT INTO `t_zone` VALUES ('265', 'Malawi', 113, '马拉维', 1, 'M');
INSERT INTO `t_zone` VALUES ('60', 'Malaysia', 114, '马来西亚', 1, 'M');
INSERT INTO `t_zone` VALUES ('960', 'Maldives', 115, '马尔代夫', 1, 'M');
INSERT INTO `t_zone` VALUES ('223', 'Mali', 116, '马里', 1, 'M');
INSERT INTO `t_zone` VALUES ('356', 'Malta', 117, '马耳他', 1, 'M');
INSERT INTO `t_zone` VALUES ('1670', 'Mariana Is', 118, '马里亚那群岛', 1, 'M');
INSERT INTO `t_zone` VALUES ('596', 'Martinique', 119, '马提尼克', 1, 'M');
INSERT INTO `t_zone` VALUES ('230', 'Mauritius', 120, '毛里求斯', 1, 'M');
INSERT INTO `t_zone` VALUES ('52', 'Mexico', 121, '墨西哥', 1, 'M');
INSERT INTO `t_zone` VALUES ('373', 'Moldova, Republic of', 122, '摩尔多瓦', 1, 'M');
INSERT INTO `t_zone` VALUES ('377', 'Monaco', 123, '摩纳哥', 1, 'M');
INSERT INTO `t_zone` VALUES ('976', 'Mongolia', 124, '蒙古', 1, 'M');
INSERT INTO `t_zone` VALUES ('1664', 'Montserrat Is', 125, '蒙特塞拉特岛', 1, 'M');
INSERT INTO `t_zone` VALUES ('212', 'Morocco', 126, '摩洛哥', 1, 'M');
INSERT INTO `t_zone` VALUES ('258', 'Mozambique', 127, '莫桑比克', 1, 'M');
INSERT INTO `t_zone` VALUES ('264', 'Namibia', 129, '纳米比亚', 1, 'N');
INSERT INTO `t_zone` VALUES ('674', 'Nauru', 130, '瑙鲁', 1, 'N');
INSERT INTO `t_zone` VALUES ('977', 'Nepal', 131, '尼泊尔', 1, 'N');
INSERT INTO `t_zone` VALUES ('599', 'Netheriands Antilles', 79, '荷属安的列斯', 1, 'H');
INSERT INTO `t_zone` VALUES ('31', 'Netherlands', 80, '荷兰', 1, 'H');
INSERT INTO `t_zone` VALUES ('64', 'New Zealand', 179, '新西兰', 1, 'X');
INSERT INTO `t_zone` VALUES ('505', 'Nicaragua', 132, '尼加拉瓜', 1, 'N');
INSERT INTO `t_zone` VALUES ('227', 'Niger', 133, '尼日尔', 1, 'N');
INSERT INTO `t_zone` VALUES ('234', 'Nigeria', 134, '尼日利亚', 1, 'N');
INSERT INTO `t_zone` VALUES ('850', 'North Korea', 52, '朝鲜', 1, 'C');
INSERT INTO `t_zone` VALUES ('47', 'Norway', 135, '挪威', 1, 'N');
INSERT INTO `t_zone` VALUES ('968', 'Oman', 28, '阿曼', 1, 'A');
INSERT INTO `t_zone` VALUES ('92', 'Pakistan', 45, '巴基斯坦', 1, 'B');
INSERT INTO `t_zone` VALUES ('507', 'Panama', 46, '巴拿马', 1, 'B');
INSERT INTO `t_zone` VALUES ('675', 'Papua New Cuinea', 47, '巴布亚新几内亚', 1, 'B');
INSERT INTO `t_zone` VALUES ('595', 'Paraguay', 48, '巴拉圭', 1, 'B');
INSERT INTO `t_zone` VALUES ('51', 'Peru', 49, '秘鲁', 1, 'B');
INSERT INTO `t_zone` VALUES ('63', 'Philippines', 65, '菲律宾', 1, 'F');
INSERT INTO `t_zone` VALUES ('48', 'Poland', 50, '波兰', 1, 'B');
INSERT INTO `t_zone` VALUES ('351', 'Portugal', 138, '葡萄牙', 1, 'P');
INSERT INTO `t_zone` VALUES ('1787', 'Puerto Rico', 51, '波多黎各', 1, 'B');
INSERT INTO `t_zone` VALUES ('974', 'Qatar', 96, '卡塔尔', 1, 'K');
INSERT INTO `t_zone` VALUES ('262', 'Reunion', 106, '留尼旺', 1, 'L');
INSERT INTO `t_zone` VALUES ('40', 'Romania', 107, '罗马尼亚', 1, 'L');
INSERT INTO `t_zone` VALUES ('7', 'Russia', 59, '俄罗斯', 1, 'E');
INSERT INTO `t_zone` VALUES ('1758', 'Saint Lueia', 144, '圣卢西亚', 1, 'S');
INSERT INTO `t_zone` VALUES ('1784', 'Saint Vincent', 145, '圣文森特岛', 1, 'S');
INSERT INTO `t_zone` VALUES ('684', 'Samoa Eastern', 56, '东萨摩亚(美)', 1, 'D');
INSERT INTO `t_zone` VALUES ('685', 'Samoa Western', 180, '西萨摩亚', 1, 'X');
INSERT INTO `t_zone` VALUES ('378', 'San Marino', 146, '圣马力诺', 1, 'S');
INSERT INTO `t_zone` VALUES ('239', 'Sao Tome and Principe', 147, '圣多美和普林西比', 1, 'S');
INSERT INTO `t_zone` VALUES ('966', 'Saudi Arabia', 148, '沙特阿拉伯', 1, 'S');
INSERT INTO `t_zone` VALUES ('221', 'Senegal', 149, '塞内加尔', 1, 'S');
INSERT INTO `t_zone` VALUES ('248', 'Seychelles', 150, '塞舌尔', 1, 'S');
INSERT INTO `t_zone` VALUES ('232', 'Sierra Leone', 151, '塞拉利昂', 1, 'S');
INSERT INTO `t_zone` VALUES ('65', 'Singapore', 181, '新加坡', 1, 'X');
INSERT INTO `t_zone` VALUES ('421', 'Slovakia', 152, '斯洛伐克', 1, 'S');
INSERT INTO `t_zone` VALUES ('386', 'Slovenia', 153, '斯洛文尼亚', 1, 'S');
INSERT INTO `t_zone` VALUES ('677', 'Solomon Is', 154, '所罗门群岛', 1, 'S');
INSERT INTO `t_zone` VALUES ('252', 'Somali', 155, '索马里', 1, 'S');
INSERT INTO `t_zone` VALUES ('27', 'South Africa', 136, '南非', 1, 'N');
INSERT INTO `t_zone` VALUES ('34', 'Spain', 182, '西班牙', 1, 'X');
INSERT INTO `t_zone` VALUES ('94', 'Sri Lanka', 156, '斯里兰卡', 1, 'S');
INSERT INTO `t_zone` VALUES ('1758', 'St.Lucia', 108, '圣卢西亚', 1, 'L');
INSERT INTO `t_zone` VALUES ('1784', 'St.Vincent', 109, '圣文森特', 1, 'L');
INSERT INTO `t_zone` VALUES ('249', 'Sudan', 157, '苏丹', 1, 'S');
INSERT INTO `t_zone` VALUES ('597', 'Suriname', 158, '苏里南', 1, 'S');
INSERT INTO `t_zone` VALUES ('268', 'Swaziland', 159, '斯威士兰', 1, 'S');
INSERT INTO `t_zone` VALUES ('46', 'Sweden', 140, '瑞典', 1, 'R');
INSERT INTO `t_zone` VALUES ('41', 'Switzerland', 141, '瑞士', 1, 'R');
INSERT INTO `t_zone` VALUES ('963', 'Syria', 183, '叙利亚', 1, 'X');
INSERT INTO `t_zone` VALUES ('886', 'Taiwan', 3, '台湾省', 1, 'T');
INSERT INTO `t_zone` VALUES ('992', 'Tajikstan', 161, '塔吉克斯坦', 1, 'T');
INSERT INTO `t_zone` VALUES ('255', 'Tanzania', 162, '坦桑尼亚', 1, 'T');
INSERT INTO `t_zone` VALUES ('66', 'Thailand', 163, '泰国', 1, 'T');
INSERT INTO `t_zone` VALUES ('228', 'Togo', 57, '多哥', 1, 'D');
INSERT INTO `t_zone` VALUES ('676', 'Tonga', 164, '汤加', 1, 'T');
INSERT INTO `t_zone` VALUES ('1809', 'Trinidad and Tobago', 165, '特立尼达和多巴哥', 1, 'T');
INSERT INTO `t_zone` VALUES ('216', 'Tunisia', 166, '突尼斯', 1, 'T');
INSERT INTO `t_zone` VALUES ('90', 'Turkey', 167, '土耳其', 1, 'T');
INSERT INTO `t_zone` VALUES ('993', 'Turkmenistan', 168, '土库曼斯坦', 1, 'T');
INSERT INTO `t_zone` VALUES ('256', 'Uganda', 171, '乌干达', 1, 'W');
INSERT INTO `t_zone` VALUES ('380', 'Ukraine', 172, '乌克兰', 1, 'W');
INSERT INTO `t_zone` VALUES ('971', 'United Arab Emirates', 29, '阿拉伯联合酋长国', 1, 'A');
INSERT INTO `t_zone` VALUES ('44', 'United Kiongdom', 193, '英国', 1, 'Y');
INSERT INTO `t_zone` VALUES ('1', 'United States of America', 128, '美国', 1, 'M');
INSERT INTO `t_zone` VALUES ('598', 'Uruguay', 173, '乌拉圭', 1, 'W');
INSERT INTO `t_zone` VALUES ('233', 'Uzbekistan', 174, '乌兹别克斯坦', 1, 'W');
INSERT INTO `t_zone` VALUES ('58', 'Venezuela', 175, '委内瑞拉', 1, 'W');
INSERT INTO `t_zone` VALUES ('84', 'Vietnam', 194, '越南', 1, 'Y');
INSERT INTO `t_zone` VALUES ('967', 'Yemen', 195, '也门', 1, 'Y');
INSERT INTO `t_zone` VALUES ('381', 'Yugoslavia', 137, '南斯拉夫', 1, 'N');
INSERT INTO `t_zone` VALUES ('243', 'Zaire', 200, '扎伊尔', 1, 'Z');
INSERT INTO `t_zone` VALUES ('260', 'Zambia', 201, '赞比亚', 1, 'Z');
INSERT INTO `t_zone` VALUES ('263', 'Zimbabwe', 89, '津巴布韦', 1, 'J');
